"""MDP file templates for the v0 / v1 pipeline.

The templates are deliberately minimal but match the canonical GROMACS
lysozyme tutorial defaults. They are formatted strings; render_*() helpers
substitute configurable parameters (step count, temperatures, etc.).

The rendered template's sha256 hash feeds StepFingerprint.tool_components,
so changing a template invalidates downstream steps that depend on it.
"""

from __future__ import annotations

from pathlib import Path

# ---- Ion-placement preprocessor mdp ------------------------------------

IONS_MDP = """\
; ions.mdp — used by gmx grompp before genion to produce a .tpr
; for ion insertion. No real dynamics is run; this is a placeholder.

integrator      = steep
nsteps          = 0
cutoff-scheme   = Verlet
nstlist         = 1
rlist           = 1.0
coulombtype     = PME
rcoulomb        = 1.0
vdw-type        = cut-off
rvdw            = 1.0
pbc             = xyz
"""


# ---- Energy minimization -----------------------------------------------

EM_MDP_TEMPLATE = """\
; em.mdp — steepest-descent energy minimization for v0 golden path.

integrator      = steep
nsteps          = {step_cap}
emtol           = {fmax_tol_kjmolnm}
emstep          = 0.01
cutoff-scheme   = Verlet
nstlist         = 10
rlist           = 1.0
coulombtype     = PME
rcoulomb        = 1.0
vdw-type        = cut-off
rvdw            = 1.0
pbc             = xyz
nstenergy       = 10
nstlog          = 10
"""


def render_em_mdp(*, step_cap: int = 1000, fmax_tol_kjmolnm: float = 1000.0) -> str:
    return EM_MDP_TEMPLATE.format(step_cap=step_cap, fmax_tol_kjmolnm=fmax_tol_kjmolnm)


# ---- NVT equilibration -------------------------------------------------

# Position-restrained NVT equilibration. Restraints are pulled in via the
# `define = -DPOSRES` line which activates posre.itp generated by pdb2gmx.
NVT_MDP_TEMPLATE = """\
; nvt.mdp — NVT equilibration with position restraints on the protein heavy atoms.

define              = -DPOSRES
integrator          = md
nsteps              = {nsteps}
dt                  = {dt_ps}

; Output control
nstxout             = 0
nstvout             = 0
nstenergy           = 100
nstlog              = 100
nstxout-compressed  = {nstxout_compressed}
compressed-x-grps   = System

; Bond constraints
continuation        = no
constraint_algorithm= lincs
constraints         = h-bonds
lincs_iter          = 1
lincs_order         = 4

; Neighbor searching
cutoff-scheme       = Verlet
nstlist             = 10
rlist               = 1.0
rcoulomb            = 1.0
rvdw                = 1.0

; Electrostatics + VdW
coulombtype         = PME
pme_order           = 4
fourierspacing      = 0.16

; Temperature coupling
tcoupl              = V-rescale
tc-grps             = Protein Non-Protein
tau_t               = 0.1     0.1
ref_t               = {temperature_K} {temperature_K}

; Pressure coupling off (NVT)
pcoupl              = no

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
gen_vel             = yes
gen_temp            = {temperature_K}
gen_seed            = {random_seed}
"""


def render_nvt_mdp(
    *,
    nsteps: int = 50000,           # 50000 * 2 fs = 100 ps
    dt_ps: float = 0.002,
    temperature_K: float = 300.0,
    random_seed: int = 42,
    nstxout_compressed: int = 5000,
) -> str:
    return NVT_MDP_TEMPLATE.format(
        nsteps=nsteps, dt_ps=dt_ps,
        temperature_K=temperature_K, random_seed=random_seed,
        nstxout_compressed=nstxout_compressed,
    )


# ---- NPT equilibration -------------------------------------------------

# NPT equilibration: turn on Parrinello-Rahman barostat, keep position
# restraints. The pre-existing velocities from NVT are continued.
NPT_MDP_TEMPLATE = """\
; npt.mdp — NPT equilibration with position restraints, continuing from NVT.

define              = -DPOSRES
integrator          = md
nsteps              = {nsteps}
dt                  = {dt_ps}

; Output control
nstxout             = 0
nstvout             = 0
nstenergy           = 100
nstlog              = 100
nstxout-compressed  = {nstxout_compressed}
compressed-x-grps   = System

; Bond constraints
continuation        = yes
constraint_algorithm= lincs
constraints         = h-bonds
lincs_iter          = 1
lincs_order         = 4

; Neighbor searching
cutoff-scheme       = Verlet
nstlist             = 10
rlist               = 1.0
rcoulomb            = 1.0
rvdw                = 1.0

; Electrostatics + VdW
coulombtype         = PME
pme_order           = 4
fourierspacing      = 0.16

; Temperature coupling
tcoupl              = V-rescale
tc-grps             = Protein Non-Protein
tau_t               = 0.1     0.1
ref_t               = {temperature_K} {temperature_K}

; Pressure coupling
pcoupl              = C-rescale
pcoupltype          = isotropic
tau_p               = 2.0
ref_p               = {pressure_bar}
compressibility     = 4.5e-5
refcoord_scaling    = com

; Periodic boundary conditions
pbc                 = xyz

; Continue velocities from NVT
gen_vel             = no
"""


def render_npt_mdp(
    *,
    nsteps: int = 50000,
    dt_ps: float = 0.002,
    temperature_K: float = 300.0,
    pressure_bar: float = 1.0,
    nstxout_compressed: int = 5000,
) -> str:
    return NPT_MDP_TEMPLATE.format(
        nsteps=nsteps, dt_ps=dt_ps,
        temperature_K=temperature_K, pressure_bar=pressure_bar,
        nstxout_compressed=nstxout_compressed,
    )


# ---- Production --------------------------------------------------------

# Production MD: no position restraints. Continues velocities + box from NPT.
PRODUCTION_MDP_TEMPLATE = """\
; production.mdp — free MD (no restraints), continuing from NPT.

integrator          = md
nsteps              = {nsteps}
dt                  = {dt_ps}

; Output control
nstxout             = 0
nstvout             = 0
nstenergy           = 1000
nstlog              = 1000
nstxout-compressed  = {nstxout_compressed}
compressed-x-grps   = System

; Bond constraints
continuation        = yes
constraint_algorithm= lincs
constraints         = h-bonds
lincs_iter          = 1
lincs_order         = 4

; Neighbor searching
cutoff-scheme       = Verlet
nstlist             = 10
rlist               = 1.0
rcoulomb            = 1.0
rvdw                = 1.0

; Electrostatics + VdW
coulombtype         = PME
pme_order           = 4
fourierspacing      = 0.16

; Temperature coupling
tcoupl              = V-rescale
tc-grps             = Protein Non-Protein
tau_t               = 0.1     0.1
ref_t               = {temperature_K} {temperature_K}

; Pressure coupling
pcoupl              = Parrinello-Rahman
pcoupltype          = isotropic
tau_p               = 2.0
ref_p               = {pressure_bar}
compressibility     = 4.5e-5

; Periodic boundary conditions
pbc                 = xyz

; Continue velocities from NPT
gen_vel             = no
"""


def render_production_mdp(
    *,
    nsteps: int = 500000,        # 500000 * 2 fs = 1 ns
    dt_ps: float = 0.002,
    temperature_K: float = 300.0,
    pressure_bar: float = 1.0,
    nstxout_compressed: int = 5000,
) -> str:
    return PRODUCTION_MDP_TEMPLATE.format(
        nsteps=nsteps, dt_ps=dt_ps,
        temperature_K=temperature_K, pressure_bar=pressure_bar,
        nstxout_compressed=nstxout_compressed,
    )


def write_mdp(path: str | Path, content: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
